config/routes.rb
SocialThingamajig::Application.routes.draw do
  resources :users do
    resources :friend_circles, only: [:new, :index]
  end

  resources :friend_circles, except: [:new, :index]

  resource :session
  resource :user_password
end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :name, :user_id, :friend_ids

  belongs_to :user

  has_many :friend_circle_memberships, foreign_key: :circle_id
  has_many :friends, through: :friend_circle_memberships, source: :member
end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :circle_id, :member_id

  belongs_to :friend_circle, foreign_key: :circle_id, class_name: "FriendCircle"
  belongs_to :member, foreign_key: :member_id, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :email, :password
   attr_accessor :password

   before_validation :set_session_token, :set_password_reset_token,
                     :set_password_digest, :on => :create

   validates :email, :password_digest, :session_token, :presence => true

   has_many :friend_circles
   has_many :friend_circle_memberships, foreign_key: :member_id
   has_many :friends, through: :friend_circle, source: :friends


   def set_password_reset_token
     self.password_reset_token = SecureRandom::urlsafe_base64(16)
   end

   def set_session_token
     self.session_token = SecureRandom::urlsafe_base64(16)
   end

   def set_password_digest
     self.password_digest = BCrypt::Password.create(self.password)
   end

   def reset_session_token!
     set_session_token
     self.save!
   end

   def reset_password!(new_password)
     set_password_reset_token
     self.password = new_password
     set_password_digest
     save!
   end

   def self.find_by_credentials(params = {:email => nil, :password => nil})
     user = User.find_by_email(params[:email])
     return user if !user.nil? && user.is_password?(params[:password])
     nil
   end

   def is_password?(secret)
     BCrypt::Password.new(self.password_digest).is_password?(secret)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # protect_from_forgery

  before_filter :redirect_unless_logged_in


end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def show
    @friend_circle = FriendCircle.find(params[:id])
  end

  def index
  end

  def new
    @friend_circle = FriendCircle.new
  end

  def create
    params[:friend_circle][:user_id] = current_user.id
    @friend_circle = FriendCircle.new(params[:friend_circle])
    if @friend_circle.save
      flash[:notice]="new friend circle created!"
      redirect_to friend_circle_url(@friend_circle)
    else
      flash[:error] ||= []
      flash[:error] << @friend_circle.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :redirect_unless_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user])
    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new
      flash.now[:errors] ||= []
      flash.now[:errors] << "Invalid email or password"
      render :new
    end
  end

  def destroy
    log_out!
  end
end

app/controllers/user_passwords_controller.rb
class UserPasswordsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      PasswordMailer.password_reset(user).deliver!
      redirect_to new_session_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << "not a valid email"
      render :new
    end
  end

  def update
    current_user.reset_password!(params[:user][:password])
    redirect_to new_session_url
  end

  def edit
    @user = User.find_by_password_reset_token(params[:password_reset_token])

    log_in_user!(@user)
    puts "------------------------------------"
    puts current_user.email
    render :edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :redirect_unless_logged_in, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors]=@user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    @current_user = user
  end

  def log_out!
    if logged_in?
      current_user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_session_url
    end
  end

  def authenticate
    redirect_to new_sessions_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def redirect_unless_logged_in
    unless logged_in?
      flash[:errors] = ["you must be logged in to see this page"]
      redirect_to new_session_url
    end
  end
end

app/helpers/user_passwords_helper.rb
module UserPasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/new.html.erb
<h1>Create a new Friend Circle</h1>

<form action="<%= friend_circles_url %>" method="POST">

  <label for="friend_circle_name">Circle Name</label>
  <input type="text" name="friend_circle[name]" id="friend_circle_name">
  <br>

  <% User.all.each do |user| %>
    <input  type="checkbox"
            name="friend_circle[friend_ids][]"
            value="<%= user.id %>"
            id="user_friend_<%= user.email %>">
    <label for="user_friend_<%= user.email %>"><%= user.email %></label>
    <br>
  <% end %>

  <input type="submit" value="Create New Circle">
</form>

app/views/friend_circles/show.html.erb
<h1><%= @friend_circle.name %></h1>

<ul>
  <% @friend_circle.friends.each do |friend| %>
    <li><%= friend.email %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThingamajig</title>
  <% stylesheet_link_tag    "application", :media => "all" %>
  <% javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<%= error %><br>
		<% end %>
	<% end %>

	<% if logged_in? %>
			Logged in as <%=current_user.email %>
			<%= button_to("Logout", session_url, :method => :delete)%>
			<%else%>

			<%end%>
<%= yield %>

</body>
</html>

app/views/user_passwords/edit.html.erb
<h1>Reset your password</h1>

<form action="<%= user_password_url %>" method="POST">
	<input type="hidden" name="_method" value = "PUT">
	<label for ="user_password">New Password</label>
	<input type = "text" name = "user[password]" id = "user_password"> <br>
	<input type = "submit" value = "Reset Password">
</form>

app/views/user_passwords/new.html.erb
<h1>Forgot your password?</h1>

<form action="<%= user_password_url %>" method="POST">
	<label for="email">Enter your email address</label>
	<input type="text" name="email" id="email">

	<input type="submit" value="Reset my password">
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
	<input 	type="hidden"
					name="authenticity_token"
					value="<%= form_authenticity_token %>"
	>
	<label for = "user_email">Email</label>
	<input type = "text" id = "user_email"
	name = "user[email]" value = "<%= @user.email %>"> <br>

	<label for = "user_password">Password</label>
	<input type = "text" id = "user_password"
	name = "user[password]" value = "<%= @user.password %>"> <br>

	<input type = "submit" value = "Sign Up">

</form>

app/views/users/show.html.erb
<h1>User info for <%= @user.email %></h1>

<% @user.attributes.each do |attr, val| %>
  <%= "#{attr} : #{val}" %><br>
<% end %>

<br>

<h4>
  <%= link_to "Create a new friend circle", new_user_friend_circle_url(@user) %>
</h4>
<br>

<h3>Friend Circles</h3>
<% @user.friend_circles.each do |circle| %>
  <%= link_to circle.name, friend_circle_url(circle) %>
<% end %>